### ISSUE TITLE
Uncaught TypeError: clear is not a function

### ISSUE THREAD

**Issue by isJudy** [kapetan/electron-drag#12]
after " npm install electron-drag " ,then,I use

var drag = require('electron-drag');
 
// Pass a query selector or a dom element to the function.
// Dragging the element will drag the whole window.
var clear = drag('#element');
 
// Call the returned function to make the element undraggable again.
clear();

but get the wrong msg " Uncaught TypeError: clear is not a function "

would friends know why

**Comment by kapetan** [comment]
Check `drag.supported` to see if the module is supported on your system. It only works on Windows and MacOS.

**Comment by isJudy** [comment]
> Check `drag.supported` to see if the module is supported on your system. It only works on Windows and MacOS.

Thank you for your reply .sorry I forget to provide the msg that my system is MacOS.I still can not figure it out

**Comment by RacerDelux** [comment]
Any update on this?

**Comment by kapetan** [comment]
You have to build with the correct electron header. Hope you figured it out.

**Comment by RacerDelux** [comment]
> 
> 
> You have to build with the correct electron header. Hope you figured it out.

Would you mind posting what that correct header is for future reference?

**Comment by kapetan** [comment]
The readme has a link to the [guide](https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md).
