### ISSUE TITLE
it still show noop function

### ISSUE THREAD

**Issue by WingDust** [kapetan/electron-drag#15]
![image](https://user-images.githubusercontent.com/45911286/72718278-9a771600-3bb0-11ea-960b-0eb333578fc3.png)

![image](https://user-images.githubusercontent.com/45911286/72718392-d27e5900-3bb0-11ea-8bfd-da262da75057.png)

![image](https://user-images.githubusercontent.com/45911286/72718507-0c4f5f80-3bb1-11ea-9f30-7d5434f97e64.png)

**Comment by kapetan** [comment]
It only works on MacOS and Windows. Check the `supported` property to see if the module is supported. You also have to build with the correct Electron headers as mentioned in the readme.
