### ISSUE TITLE
Please try re-compiling or re-installing

### ISSUE THREAD

**Issue by yanlee26** [kapetan/electron-drag#18]
electron/js2c/renderer_init.js:2341 Error: The module '/Users/elliotyan/Documents/me/electron-with-sqlite3/node_modules/osx-mouse/build/Release/addon.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 76. Please try re-compiling or re-installing

**Comment by kapetan** [comment]
You have to build with the correct Electron headers as mentioned in the readme.
