### ISSUE TITLE
any plans to support linux platform?

### ISSUE THREAD

**Issue by bruceauyeung** [kapetan/electron-drag#20]
looks like linux-mouse is missing…

**Comment by kapetan** [comment]
Sorry no plans for linux.

**Comment by Heath123** [comment]
Oh, why not?

**Comment by Heath123** [comment]
That makes it sort of useless because we can't expect it to work everywhere (and it my case I'm trying to contribute to an Electron wrapper for Office work on Linux)

**Comment by Heath123** [comment]
Apparently there's `electron.screen.getCursorScreenPoint()`

**Comment by Heath123** [comment]
https://github.com/electron/electron/issues/1354#issuecomment-404348957

**Comment by Heath123** [comment]
If it's to do with market share, Linux is about as common as Mac OS among developers: https://insights.stackoverflow.com/survey/2019?utm_content=launch-post&utm_source=twitter&utm_medium=social&utm_campaign=dev-survey-2019#technology-_-developers-primary-operating-systems

**Comment by kapetan** [comment]
I don't plan on adding Linux support myself. But I'm open to a `linux-mouse` like implementation which can be included in `electron-drag`.

I didn't know about `electron.screen.getCursorScreenPoint()`, maybe that's a solution.

**Comment by Heath123** [comment]
Not sure if it works the same as the native verion, though. I'll probably look into it

**Comment by Heath123** [comment]
OK, it does work even when the window is defocused or the cursor is out of the window so that seems useful
