### ISSUE TITLE
Installing Problem

### ISSUE THREAD

**Issue by Eldeveloper-1** [kapetan/electron-drag#21]
I use `npm install electron-drag` to install electron-drag in my electron app.
But it report some errors.  Here is the install error reports.
It might be more easily to read in a file 
[report.txt](https://github.com/kapetan/electron-drag/files/5911195/report.txt)

My system is Windows 10 x64
Also I think I have installed `windows-build-tools` and `node-gyp`  correctly.
> C:\Users\intmain>node-gyp list
> gyp info it worked if it ends with ok
> gyp info using node-gyp@7.1.2
> gyp info using node@14.15.4 | win32 | x64
> 14.15.4
> gyp info ok

**Comment by kapetan** [comment]
Have you tried building using electron headers as mentioned in the readme: https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md

**Comment by Eldeveloper-1** [comment]
I tried. Still, the same error report

> C:\Users\intmain\Desktop\DateApp_3>npm install --save-dev electron-rebuild
> npm WARN deprecated har-validator@5.1.5: this
> npm notice created a lockfile as package-lock.json. You should commit this file.
> npm WARN DateApp_3@1.0.0 No description
> npm WARN DateApp_3@1.0.0 No repository field.
> 
> \+ electron-rebuild@2.3.4
> removed 4 packages and updated 1 package in 13.523s

**Comment by Eldeveloper-1** [comment]
the error was occurred during the installing, not compiling or running my app

**Comment by kapetan** [comment]
What's the error you get when running electron-rebuild?

**Comment by Eldeveloper-1** [comment]
Another problem... 
```
C:\Users\intmain\Desktop\DateApp_3>node_modules\.bin\electron-rebuild

An unhandled error occurred inside electron-rebuild
Unable to find electron's version number, either install it or specify an explicit version

Error: Unable to find electron's version number, either install it or specify an explicit version
    at C:\Users\intmain\Desktop\DateApp_3\node_modules\electron-rebuild\lib\src\cli.js:82:19
```
the electron module was installed globally, did i run it mistakenly or i need to add some infomations to packet.json?
```
C:\Users\intmain\Desktop\DateApp_3>electron -v

v11.2.1
```
