### ISSUE TITLE
Build Errors for osx-mouse on windows

### ISSUE THREAD

**Issue by kneumei** [kapetan/electron-drag#3]
When I do `npm install` on windows, I get an error telling me it can't build osx-mouse. Is there a way to specify that I only want it to try to build win-mouse?

I did some googling and found this on SO (http://stackoverflow.com/questions/15176082/npm-package-json-os-specific-dependency), but none of the solutions seem that great. Wondering if there is anything else.

I don't mind the errors that much when working locally, but my CI server doesn't like them at all and fails the build. 

```
C:\MyApp\node_modules\electron-drag\node_modules\osx-mouse>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  addon.cc
  mouse.cc
c:\MyApp\node_modules\electron-drag\node_modules\osx-mouse\source\mouse.h(4): fatal error C1083: Cannot open include file: 'CoreGraphics/CoreGraphics.h': No such file or directory (..\source\mouse.cc) [C:\MyApp\node_modules\e lectron-drag\node_modules\osx-mouse\build\addon.vcxproj]
c:\MyApp\node_modules\electron-drag\node_modules\osx-mouse\source\mouse.h(4): fatal error C1083: Cannot open include file: 'CoreGraphics/CoreGraphics.h': No such file or directory (..\source\addon.cc) [C:\MyApp\node_modules\e lectron-drag\node_modules\osx-mouse\build\addon.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\MyApp\node_modules\electron-drag\node_modules\osx-mouse
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
```

**Comment by kneumei** [comment]
I tested adding the OS field to the package.json file for osx-mouse, and it fixed my problem. Is this workable or are there other considerations?

See https://github.com/kneumei/osx-mouse/blob/master/package.json#L32

**Comment by kapetan** [comment]
Thanks for reporting the issue. I'll try out your solution.

`electron-drag` should still work on windows, since `osx-mouse` is an optional dependency. The problem you are having is the error message in the console. Am I understanding that correctly?

**Comment by kneumei** [comment]
Yes, `electron-drag` still works just fine on windows. It's just that when I do `npm install` on my project that has a dependency on `electron-drag`, it tries to build both `osx-mouse` and `win-mouse`. The `win-mouse` dependency builds fine. However the `osx-mouse` produces some errors. Like I said, it's fine and I can just ignore the errors when I'm building locally on my machine. But my CI sees those errors and fails my build.

So the proposal is just to add `"os":["darwin"]` to the `package.json` for `osx-mouse`. It solves my problem, but don't know enough to know if it has other implications (e.g. is there a use case for ever building `osx-mouse` on windows?)

**Comment by kapetan** [comment]
There is never a need to build `osx-mouse` on windows (same for `win-mouse` on OS X). I didn't know about the `os` field in package.json, I'll look into it.

**Comment by kapetan** [comment]
Thanks for the pull-requests. I've bumped the versions in electron-drag. It's out in 1.1.0.

**Comment by yuanyuZQ** [comment]
i met the same wrong ,but i can't install electron-drag,
![image](https://user-images.githubusercontent.com/22787985/56273676-c7812e80-612f-11e9-9577-9d42402f2822.png)
please help!
