### ISSUE TITLE
Can't build on windows x64

### ISSUE THREAD

**Issue by alexpouliquen** [kapetan/electron-drag#5]
Hello,

Since a week I tried everything to fix compilation error : including reinstalling node-gyp, all the vs libraries, cleaning caches... There is no way I can build my app with your module.

When I install the module, I do a `node-gyp configure && node-gyp rebuild` and it's give me theses errors:

`Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  bufferutil.cc
  win_delay_load_hook.cc
c1xx : fatal error C1083: Cannot open source file: '..\src\bufferutil.cc': No such file or directory [D:\Code\XXX\node_modules\electron-drag\build\bufferutil.vcxproj]
  validation.cc
  win_delay_load_hook.cc
c1xx : fatal error C1083: Cannot open source file: '..\src\validation.cc': No such file or directory [D:\Code\XXX\node_modules\electron-drag\build\validation.vcxproj]
gyp ERR! build error`

I have seen all the topics talking about theses errors and I didn't find a way to fix them. If there is no hop for me, it's there a way to make frameless window dragable properly ?

**Comment by kapetan** [comment]
I don't have access to a windows machine at the moment so it might take me some time to check it out.

**Comment by kapetan** [comment]
I tried testing it on Window 10 (64-bit) with newest electron prebuilt version (1.4.15) and it works as expected. Are you sure you are [compiling the module correctly](https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md) as it says in the readme?
